name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "0.15.8"

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Build (using normal Spago config)
        run: spago build

      - name: Run tests
        run: spago -x test.dhall test
